### ISSUE TITLE
Crash in ball devices

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf#783] opened 2017-02-18 17:08 UTC
I've attached a zip of a log from a ball device crash from BnD. This was started via mpf-monitor with the smart virtual platform. I think I just pressed start and it crashed. I have not been able to reproduce it.

Usually I wouldn't post this as an issue, but I figured that since we're looking at the ball devices now, I'd post it. Unfortunately I didn't have full logging for ball devices enabled, but I did for the event manager so maybe that helps? Feel free to just close this too if you want.

[ball device crash - game start via monitor - maybe clicked on wrong switch.log.zip](https://github.com/missionpinball/mpf/files/785182/ball.device.crash.-.game.start.via.monitor.-.maybe.clicked.on.wrong.switch.log.zip)

**Comment by jabdoa2** [comment] 2017-02-19 12:09
Duplicate of #770 which is fixed in PR #774

**Closed as completed by jabdoa2** 2017-02-19 12:09 UTC
Labels: investigation needed
