### ISSUE TITLE
Service Menu - Items sorted in wrong order

### ISSUE THREAD

**Issue by MarkInc666** [missionpinball/mpf#794] opened 2017-02-28 16:50 UTC
Items in the service menu, for example switches, are sorted in alphabetical order.
This causes confusion.  They appear as 0, 1, 10, 11, 12, ...19, 2, 20, 21, 22, 23, ...
Should be 0, 1, 2, 3, 4, 5, 6, ...

This may be a problem for other lists too.

**Comment by F4b1-** [comment] 2017-08-19 11:06
Hi there, 
I picked this issue as a starting point for working on mission pinball. I might just need someone to point me in the right direction. I know there's a service menu I can access while a machine is running. (I am using demo-man right now) but this only contains the entries "settings", "coil test" and "switch test". No overview of all the switches or other items. If I run one of the dev examples I get a UI in the terminal that contains such a list, alphabetically ordered, that's is created by the TextUI class but that's not what you were referring to here, right?

**Comment by MarkInc666** [comment] 2017-08-19 14:08
If you go into service menu.  Then select coil test.
If you use the UP/DOWN keys to cycle through the drivers, they are neither in coil number order or alphabetical order.  I expect them to be listed as 0,1,2,3,...30,31,32,... etc.   
I think the   self.machine.service.get_coil_map() function (called around line 149 in service.py) needs to sort them properly.

**Comment by F4b1-** [comment] 2017-09-13 11:40
Hey, I opened a pull request a while back.  A couple of tests are failing. A lot of them don't really seem to be connected to the changes I made. I somehow get these test failures even I undo my changes and run them again. Any insight on this? Thanks

**Comment by jabdoa2** [comment] 2017-09-13 12:05
@F4b1- I did not look at the PR because of the failed tests. Sorry for that.

Looks like the test failures are caused by unrelated problems which existed at the time where you branched off dev. You could rebase to current dev. However, since this is a very small change it should be fine anyways. I added some comments to the PR itself.

**Comment by RoseAndres** [comment] 2017-10-23 13:44
Is this issue still open or has it been fixed with @F4b1-'s commit?

**Comment by jabdoa2** [comment] 2017-10-23 14:16
This is already fixed. We use natural sort on the strings now.

**Closed as completed by jabdoa2** 2017-10-23 14:16 UTC
Labels: bug, help wanted
