### ISSUE TITLE
Another Asyncio crash from ball controller

### ISSUE THREAD

**Issue by GabeKnuth** [missionpinball/mpf#772] opened 2017-02-15 19:37 UTC
This is the first one that happened. I don't have a verbose log for it, so it might not be that helpful. For this, Ball 2 started, and I plunged it really quickly, then it crashed. I don't know if any of that is relevant, though. 

Log attached.
[ballcontroller crash.log.zip](https://github.com/missionpinball/mpf/files/778185/ballcontroller.crash.log.zip)

**Comment by jabdoa2** [comment] 2017-02-16 21:38
This is another variant/duplicate of the race in #769

**Closed as completed by jabdoa2** 2017-02-16 21:38 UTC
Labels: bug
